name: tis-test-host-capa_linux

on:
  workflow_dispatch:  

jobs:
  run-build-wapt-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Download binary
        run: |
          curl -L "https://wapt.tranquil.it/wapt/releases/wapt-2.6.0.16613-4de25b0a/tis-waptagent-2.6.0.16613-4de25b0a-amd64.deb" -o "/tmp/waptsetup.deb"
        shell: bash

      - name: Install wapt
        run: |
          sudo apt-get install /tmp/waptsetup.deb -y
        shell: bash

      - name: Run updatepackage
        run: |
          sudo /opt/wapt/wapt-get.bin update-package-sources ./tis-test-host-capa/linux
        shell: bash

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: tis-test-host-capa-linux.wapt
          path: tis-test-host-capa/linux

      - name: Run install
        run: |
          sudo /opt/wapt/wapt-get.bin install ./tis-test-host-capa/linux
        shell: bash

      - name: Run session-setup
        run: |
          sudo /opt/wapt/wapt-get.bin session-setup ALL
        shell: bash

      - name: Run audit
        run: |
          sudo /opt/wapt/wapt-get.bin audit ./tis-test-host-capa/linux
        shell: bash

      - name: Run remove
        run: |
          sudo /opt/wapt/wapt-get.bin uninstall ./tis-test-host-capa/linux
        shell: bash
            